### ISSUE TITLE
Support checking Python code

### ISSUE THREAD

**Issue by MatthewHambley** [MetOffice/stylist#11]
Obviously it would be foolish to implement our own style checker for Python code. There are already several in existence and we are unlikely to match the developer communities they already have.

However the sort of code base we are interested in handling often includes small or even large Python scripts. We would like to be able to check those as part of a unified tool.

We could imagine implementing a rule which simply subcontracts the work out to one of these existing tools.

This raises the issue of what to do about files without extensions, something which tends to happen when scripting. The current framework assumes that files will have extensions and we use them to determine how to check the file.

**Comment by matthewrmshin** [comment]
A call out to flake8 (or its library) is probably what you want.

**Comment by MatthewHambley** [comment]
This idea is still valid but there is no obvious requirement for it. As such I'm closing this ticket down so it's not just handing around unaddressed. When a requirement comes to light a new ticket can be raised.
