### ISSUE TITLE
Specify style on command-line

### ISSUE THREAD

**Issue by MatthewHambley** [MetOffice/stylist#13]
The style used for checking is current hard-wired into the code. Looking to a future where there is more than one style this is not a viable approach. Instead the style should be specified on the command line.

**Comment by matthewrmshin** [comment]
Or configuration file?

**Comment by MatthewHambley** [comment]
> Or configuration file?

Possibly but I would have to think through the logic of that.

I can see a site wanting to specify a default style. Not sure a user would but there's probably no reason to disallow it.

As mentioned in #14 I think a per-project basis would be most useful, certainly to the way I work.
