### ISSUE TITLE
Building locally on MetOffice estate?

### ISSUE THREAD

**Issue by MarekWlasak** [MetOffice/stylist#25]
What specifically do I need to do to build this?  Is it in some module list?

I have cloned the repo

```
-> python --version
python 3.6.8 :: Anaconda, Inc.

-> python setup.py                
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

```

**Comment by MarekWlasak** [comment]
@matthewrmshin  - I can hoping to try this out with Fortran code in JEDI.  What is the best way to start?

**Comment by MatthewHambley** [comment]
We use a standard Python `setup.py` script so to install you could use `python setup.py install --home`. We also make the tool available through mypi.org so you might use `python -m pip install stylist`.

**Comment by MatthewHambley** [comment]
I'm assuming this question is now answered.
