### ISSUE TITLE
Incorrect warnings about implicit none

### ISSUE THREAD

**Issue by Beliavsky** [MetOffice/stylist#27]
When implicit none appears at the beginning of a module, there is no need for implicit none to appear in individual procedures, but stylist warns about this. For example, for the code https://github.com/fortran-lang/stdlib/blob/master/src/stdlib_ascii.f90 stylist says

Found 20 issues
stdlib_ascii.f90: Function 'is_alpha' is missing an implicit statement
stdlib_ascii.f90: Function 'is_alphanum' is missing an implicit statement
stdlib_ascii.f90: Function 'is_ascii' is missing an implicit statement
stdlib_ascii.f90: Function 'is_control' is missing an implicit statement
stdlib_ascii.f90: Function 'is_digit' is missing an implicit statement
stdlib_ascii.f90: Function 'is_octal_digit' is missing an implicit statement
stdlib_ascii.f90: Function 'is_hex_digit' is missing an implicit statement
stdlib_ascii.f90: Function 'is_punctuation' is missing an implicit statement
stdlib_ascii.f90: Function 'is_graphical' is missing an implicit statement
stdlib_ascii.f90: Function 'is_printable' is missing an implicit statement
stdlib_ascii.f90: Function 'is_lower' is missing an implicit statement
stdlib_ascii.f90: Function 'is_upper' is missing an implicit statement
stdlib_ascii.f90: Function 'is_white' is missing an implicit statement
stdlib_ascii.f90: Function 'is_blank' is missing an implicit statement
stdlib_ascii.f90: Function 'char_to_lower' is missing an implicit statement
stdlib_ascii.f90: Function 'char_to_upper' is missing an implicit statement
stdlib_ascii.f90: Function 'to_lower' is missing an implicit statement
stdlib_ascii.f90: Function 'to_upper' is missing an implicit statement
stdlib_ascii.f90: Function 'to_title' is missing an implicit statement
stdlib_ascii.f90: Function 'reverse' is missing an implicit statement

**Comment by MatthewHambley** [comment]
I just had a look at the Fortran language standard (BS ISO/IEC 1539-1:2010) and in paragraph 5.5.3 it states "...and the default for a BLOCK construct, internal subprogram or module subprogram is the mapping in the host scoping unit." Which means you are correct.

I'm fairly sure that in the past compilers have not honoured this which is probably why we require an `implicit` statement wherever one can be specified, hence the current behaviour of the "missing implicit" rule. We should be respecting the standard as written with an option for the current behaviour.
