### ISSUE TITLE
meaning of KindPattern rule

### ISSUE THREAD

**Issue by Beliavsky** [MetOffice/stylist#39]
Thanks for the project. It flags several common code defects. Now to my question.

For config.ini

```
[file-pipe]
x90=fortran:pfp:fpp

[style.multiple]
rules = FortranCharacterset, MissingOnly, MissingImplicit, MissingPointerInit, KindPattern(integer=r'.*_jazz', real=r'.*_metal')
```
and code good_style.f90

```
module m
implicit none
integer, parameter :: dp = kind(1.0d0)  
contains
function sum_mat(x) result(xsum)
real(kind=dp), intent(in) :: x(:,:)
real(kind=dp)             :: xsum
integer                   :: i,j
xsum = 0.0
do i=1,size(x,1)
   do j=1,size(x,2)
      xsum = xsum + x(i,j)
   end do
end do
end function sum_mat
end module m
!
program main
use m, only: dp, sum_mat
implicit none
real(kind=dp) :: x(2,3)
integer, pointer :: p => null()
x = 10.0
print*,sum_mat(x)
allocate(p)
p = 5
print*,"p=",p
end program main
```
`stylist -verbose -configuration config.ini good_style.f90` says

```
Examining: good_style.f90
Style: Style
Rule: FortranCharacterset - Passed
Rule: MissingOnly - Passed
Rule: MissingImplicit - Passed
Rule: MissingPointerInit - Passed
Rule: KindPattern - Failed
good_style.f90: 6: Kind 'kind=dp' found for real variable 'x(:, :)' does not fit the pattern /.*_metal/.
good_style.f90: 7: Kind 'kind=dp' found for real variable 'xsum' does not fit the pattern /.*_metal/.
good_style.f90: 21: Kind 'kind=dp' found for real variable 'x(2, 3)' does not fit the pattern /.*_metal/.
Found 3 issues

```

There is a lot of Fortran code with declarations such as real*8, which stylist objects to, but `real(kind=dp)` where `dp` is a named constant is standard-conforming and commonly done. What is stylist objecting to? What form of double precision declaration does it want?

**Comment by stevewardle** [comment]
There is nothing wrong with what you have defined in the code; but where you have configured `stylist` and put:

`KindPattern(integer=r'.*_jazz', real=r'.*_metal')`

You are telling `stylist` how you want any kinded integer or real variables to be declared.  If you intended to use the parameter `dp` for your real precision everywhere then you would configure it as:

`KindPattern(real=r'dp')`

And then going forward `stylist` would catch any cases in your project's code where the author has forgotten to declare a real with the kind `dp`
