### ISSUE TITLE
Docs for users

### ISSUE THREAD

**Issue by matthewrmshin** [MetOffice/stylist#4]
We are now missing:
* A few lines on how to install. We can do `pip install stylist`.
  * (Is it worth uploading a recipe to conda-forge as well? So we can do `conda install stylist`?)
* A few paragraphs on usage of the command line and/or the Python library.
* API docs? E.g.:
  * How to use the rules?
  * How to write a rule module (as a plugin)?
* (Can do all of these with Sphinx + Github Pages?)

**Comment by MatthewHambley** [comment]
I believe #6 answers the first point.

**Comment by MatthewHambley** [comment]
I have added [a wiki page](../wiki/Extending-Stylist) which should cover the remaining points.

**Comment by MatthewHambley** [comment]
I'm taking the thumbs up as an indication that this issue is dealt with.
