### ISSUE TITLE
Discussion of stylist at Fortran Discourse

### ISSUE THREAD

**Issue by Beliavsky** [MetOffice/stylist#42]
Not an issue, just a comment. I started a [thread](https://fortran-lang.discourse.group/t/style-checking-with-the-metoffice-stylist-tool/2960) about stylist at Fortran Discourse.

**Comment by MatthewHambley** [comment]
Thank you, much appreciated. I've noted it on a wiki page: https://github.com/MetOffice/stylist/wiki/Scrapbook
